### ISSUE TITLE
chaining modules (peepdf and url_preview) ?

### ISSUE THREAD

**Issue by 0xmilkmix** [certsocietegenerale/fame#94]
### Description

I'm trying to have `url_preview` on URLs extracted by the `peepdf` module. Since `peepdf` is not adding tags, I modified the call to `add_ioc()` to add `['extracted']` as the second parameter.

This indeed creates tags for the extracted URLs, but configuring `url_preview` to be triggered by `extracted` does not trigger anything. I didn't follow the full code path but it looked like it should be the engine that would call modules on extracted observables, correct?

#### Actual behavior

Only `peepdf` module is triggered, `url_preview` is not called following the extraction of URLs.

**edit** : looking at the code, it is probably that the module should be adding URLs using `add_extraction` instead of `add_ioc` as only extracted objects are send in the queue for processing modules like `url_preview`.

**Comment by gaelmuller** [comment]
Hello Julien :)

You are correct, module chaining is possible only with files, not with observables. You could try to patch the `peepdf` module to add URLs as "generated files" in addition to the `add_ioc` call.

Something like this should do the trick:

```python
import os
from fame.common.utils import tempdir

...

tmpdir = tempdir()
filename = os.path.join(tmpdir, 'extracted_url')
with open(filename, "w") as f:
    f.write(url)

self.register_files("url", filename)
```

This may work because FAME handles the URL type as files containing the URL.

**Comment by 0xmilkmix** [comment]
Thanks, I'll try this workaround.

Best regards
