### ISSUE TITLE
Magic on extracted files

### ISSUE THREAD

**Issue by jdkirk2** [certsocietegenerale/fame#98]
Is it possible to have FAME use magic when automatically creating new analyses for extracted files?

**Comment by gaelmuller** [comment]
Yes it is possible. It is the default behavior when there is no list of modules in the "extracted" configuration. So if you edit the global "extracted" configuration and replace the list of modules by an empty list it will use magic.

Note that because the field is required, you may need to use a space instead of an empty list.

Do not hesitate to reopen this issue if needed.
